---
namespace: trippsc2
name: netscaler
version: 1.0.5
readme: README.md
authors:
  - Jim Tarpley (@trippsc2)
description: This collection contains roles for configuring Citrix Netscaler load balancers.

license_file: 'LICENSE'

tags:
  - infrastructure
  - networking

dependencies:
  ansible.utils: '>=2.5.0'
  netscaler.adc: '>=2.6.0'
  trippsc2.adcs: '>=1.4.0'
  trippsc2.general: '>=2.9.0'
  trippsc2.hashi_vault: '>=1.7.0'

repository: https://github.com/trippsoft/ansible-collection-netscaler.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
